### ISSUE TITLE
开始请求 access_token, url => https://gitlab.com/oauth/token  获取 `access_token` 失败, error => Failed to open TCP connection to gitlab.com:443 (execution expired)

### ISSUE THREAD

**Issue by liqungang** [BestiOSDev/lg_pod_plugin#4]
如果pod 'YYText', :git => '[https://gitlab.com:/ios/yytext.git](https://gitlab.com/ios/yytext.git)', :branch => 'main'
 这个私有库开启了双因素认证（2FA），那么确实需要调整上述 Ruby（gitlab_api.rb） 脚本中处理 GitLab API 请求的方法，特别是那些涉及认证和获取 access token 的部分。GitLab 的双因素认证会增加额外的安全层，这意味着仅使用用户名和密码可能不足以获取访问令牌。以下是几个可能需要考虑的调整方向：

### 使用访问令牌（Personal Access Tokens）
GitLab 允许用户创建个人访问令牌（Personal Access Tokens），这些令牌可以用来代替密码进行 API 访问。使用个人访问令牌可以绕过双因素认证的需求，因为令牌本身就是一种安全凭证。

1. **生成个人访问令牌**：在 GitLab 用户设置中生成一个具有所需权限的个人访问令牌。
2. **修改认证方式**：在脚本中使用这个令牌代替用户名和密码进行认证。这通常意味着修改 HTTP 请求的头部，加入 `Authorization: Bearer YOUR_ACCESS_TOKEN` 字段。

### 使用 OAuth2 令牌
如果脚本中已经在使用 OAuth2 令牌进行认证，那么在用户启用双因素认证后，可能需要确保令牌的获取和刷新流程仍然有效。这可能涉及到与 GitLab OAuth2 流程更紧密的集成，包括处理额外的认证步骤。

**Comment by BestiOSDev** [comment]
主要给公司内部使用, 满足目前业务使用. 我知道可以使用令牌去访问 gitlab 服务, lg init 可以设置个人令牌. 这样不再使用 accout, password 获取 accesstoken
![image](https://github.com/BestiOSDev/lg_pod_plugin/assets/15530810/1261c251-bc9e-4f00-a2fd-fec831370b2c)

**Comment by BestiOSDev** [comment]
希望你在后边使用过程中发现问题 即使联系作者.
qq: 1060545231

**Comment by BestiOSDev** [comment]
lg_pod_plugin 提供了账户密码授权和个人令牌授权两种方式.
![image](https://github.com/BestiOSDev/lg_pod_plugin/assets/15530810/dada10a7-7f41-4651-a90c-f8bc4ab0e15b)

**Comment by BestiOSDev** [comment]
> 如果pod 'YYText', :git => '[https://gitlab.com:/ios/yytext.git](https://gitlab.com/ios/yytext.git)', :branch => 'main' 这个私有库开启了双因素认证（2FA），那么确实需要调整上述 Ruby（gitlab_api.rb） 脚本中处理 GitLab API 请求的方法，特别是那些涉及认证和获取 access token 的部分。GitLab 的双因素认证会增加额外的安全层，这意味着仅使用用户名和密码可能不足以获取访问令牌。以下是几个可能需要考虑的调整方向：
> 
> ### 使用访问令牌（Personal Access Tokens）
> GitLab 允许用户创建个人访问令牌（Personal Access Tokens），这些令牌可以用来代替密码进行 API 访问。使用个人访问令牌可以绕过双因素认证的需求，因为令牌本身就是一种安全凭证。
> 
> 1. **生成个人访问令牌**：在 GitLab 用户设置中生成一个具有所需权限的个人访问令牌。
> 2. **修改认证方式**：在脚本中使用这个令牌代替用户名和密码进行认证。这通常意味着修改 HTTP 请求的头部，加入 `Authorization: Bearer YOUR_ACCESS_TOKEN` 字段。
> 
> ### 使用 OAuth2 令牌
> 如果脚本中已经在使用 OAuth2 令牌进行认证，那么在用户启用双因素认证后，可能需要确保令牌的获取和刷新流程仍然有效。这可能涉及到与 GitLab OAuth2 流程更紧密的集成，包括处理额外的认证步骤。

1.1.8.2 版本已经修复了这个问题.
